nginx:
    build: ./load_balancer
    links:
        - home_on_rails:home_on_rails
        - auth:auth
    ports:
        - "80:80"
home_on_rails:
    build: ./rails
    links:
        - db
    ports:
        - "3000"
    environment:
        - ENV_NAME=production
        - repo=http://github.com/ricardobaumann/home_on_rails
        - name=home_on_rails
        - branch=develop
db:
    image: mysql/mysql-server
    expose:
     - 3306
    environment:
      MYSQL_DATABASE: home_on_rails
      MYSQL_USER: home_on_rails
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
auth:
    build: ./auth
    ports:
        - "3000"