nginx:
    build: ./load_balancer
    links:
        - ranking:ranking
        - mobile:mobile
    ports:
        - "80:80"
ranking:
    build: ./ranking
    links:
        - mongo
    ports:
        - "3000"
mobile:
    build: ./mobile
    ports:
        - "2000"
mongo:
    image: mongo
    ports:
        - "27017"